// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RegisterPlayerReducer from "../register_player_reducer";
import CreateSessionReducer from "../create_session_reducer";
import JoinSessionReducer from "../join_session_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import StartSessionReducer from "../start_session_reducer";
import PauseSessionReducer from "../pause_session_reducer";
import ResumeSessionReducer from "../resume_session_reducer";
import EndSessionReducer from "../end_session_reducer";
import ConfigureSessionRuntimeReducer from "../configure_session_runtime_reducer";
import UpdateSessionStateReducer from "../update_session_state_reducer";
import SpawnEntityReducer from "../spawn_entity_reducer";
import UpdateEntityTransformReducer from "../update_entity_transform_reducer";
import DespawnEntityReducer from "../despawn_entity_reducer";
import UpsertEntityComponentReducer from "../upsert_entity_component_reducer";
import RemoveEntityComponentReducer from "../remove_entity_component_reducer";
import UpsertSessionResourceReducer from "../upsert_session_resource_reducer";
import RemoveSessionResourceReducer from "../remove_session_resource_reducer";
import EmitSessionEventReducer from "../emit_session_event_reducer";
import SubmitInputFrameReducer from "../submit_input_frame_reducer";
import CaptureSnapshotReducer from "../capture_snapshot_reducer";
import PruneSnapshotsReducer from "../prune_snapshots_reducer";
import AssignPlayerPawnReducer from "../assign_player_pawn_reducer";
import UpdatePlayerPresenceReducer from "../update_player_presence_reducer";
import AdjustPlayerScoreReducer from "../adjust_player_score_reducer";
import UpsertPrivateStateReducer from "../upsert_private_state_reducer";
import RemovePrivateStateReducer from "../remove_private_state_reducer";
import StartTickLoopReducer from "../start_tick_loop_reducer";
import StopTickLoopReducer from "../stop_tick_loop_reducer";

export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type StartSessionParams = __Infer<typeof StartSessionReducer>;
export type PauseSessionParams = __Infer<typeof PauseSessionReducer>;
export type ResumeSessionParams = __Infer<typeof ResumeSessionReducer>;
export type EndSessionParams = __Infer<typeof EndSessionReducer>;
export type ConfigureSessionRuntimeParams = __Infer<typeof ConfigureSessionRuntimeReducer>;
export type UpdateSessionStateParams = __Infer<typeof UpdateSessionStateReducer>;
export type SpawnEntityParams = __Infer<typeof SpawnEntityReducer>;
export type UpdateEntityTransformParams = __Infer<typeof UpdateEntityTransformReducer>;
export type DespawnEntityParams = __Infer<typeof DespawnEntityReducer>;
export type UpsertEntityComponentParams = __Infer<typeof UpsertEntityComponentReducer>;
export type RemoveEntityComponentParams = __Infer<typeof RemoveEntityComponentReducer>;
export type UpsertSessionResourceParams = __Infer<typeof UpsertSessionResourceReducer>;
export type RemoveSessionResourceParams = __Infer<typeof RemoveSessionResourceReducer>;
export type EmitSessionEventParams = __Infer<typeof EmitSessionEventReducer>;
export type SubmitInputFrameParams = __Infer<typeof SubmitInputFrameReducer>;
export type CaptureSnapshotParams = __Infer<typeof CaptureSnapshotReducer>;
export type PruneSnapshotsParams = __Infer<typeof PruneSnapshotsReducer>;
export type AssignPlayerPawnParams = __Infer<typeof AssignPlayerPawnReducer>;
export type UpdatePlayerPresenceParams = __Infer<typeof UpdatePlayerPresenceReducer>;
export type AdjustPlayerScoreParams = __Infer<typeof AdjustPlayerScoreReducer>;
export type UpsertPrivateStateParams = __Infer<typeof UpsertPrivateStateReducer>;
export type RemovePrivateStateParams = __Infer<typeof RemovePrivateStateReducer>;
export type StartTickLoopParams = __Infer<typeof StartTickLoopReducer>;
export type StopTickLoopParams = __Infer<typeof StopTickLoopReducer>;

