// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RegisterPlayerReducer from "../register_player_reducer";
import CreateSessionReducer from "../create_session_reducer";
import JoinSessionReducer from "../join_session_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import StartGameReducer from "../start_game_reducer";
import EndGameReducer from "../end_game_reducer";
import PauseGameReducer from "../pause_game_reducer";
import SubmitActionReducer from "../submit_action_reducer";
import UpdateSessionStateReducer from "../update_session_state_reducer";
import CreateObjectReducer from "../create_object_reducer";
import UpdateObjectReducer from "../update_object_reducer";
import RemoveObjectReducer from "../remove_object_reducer";
import UpdatePlayerScoreReducer from "../update_player_score_reducer";
import UpdatePlayerPrivateStateReducer from "../update_player_private_state_reducer";
import SendChatReducer from "../send_chat_reducer";
import GameTickReducer from "../game_tick_reducer";
import StartTickTimerReducer from "../start_tick_timer_reducer";
import StopTickTimerReducer from "../stop_tick_timer_reducer";

export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type EndGameParams = __Infer<typeof EndGameReducer>;
export type PauseGameParams = __Infer<typeof PauseGameReducer>;
export type SubmitActionParams = __Infer<typeof SubmitActionReducer>;
export type UpdateSessionStateParams = __Infer<typeof UpdateSessionStateReducer>;
export type CreateObjectParams = __Infer<typeof CreateObjectReducer>;
export type UpdateObjectParams = __Infer<typeof UpdateObjectReducer>;
export type RemoveObjectParams = __Infer<typeof RemoveObjectReducer>;
export type UpdatePlayerScoreParams = __Infer<typeof UpdatePlayerScoreReducer>;
export type UpdatePlayerPrivateStateParams = __Infer<typeof UpdatePlayerPrivateStateReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type GameTickParams = __Infer<typeof GameTickReducer>;
export type StartTickTimerParams = __Infer<typeof StartTickTimerReducer>;
export type StopTickTimerParams = __Infer<typeof StopTickTimerReducer>;

