// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.u64(),
  eventKind: __t.string(),
  eventScope: __t.string(),
  replicationGroup: __t.string(),
  visibilityScope: __t.string(),
  visibilityKey: __t.option(__t.string()),
  targetEntityId: __t.option(__t.u64()),
  simulationTick: __t.u32(),
  dataJson: __t.string(),
};
