// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  entityKey: __t.string().name("entity_key"),
  archetype: __t.string(),
  parentEntityId: __t.option(__t.u64()).name("parent_entity_id"),
  ownerSlot: __t.i32().name("owner_slot"),
  authority: __t.string(),
  replicationGroup: __t.string().name("replication_group"),
  zoneKey: __t.string().name("zone_key"),
  visibilityScope: __t.string().name("visibility_scope"),
  visibilityKey: __t.option(__t.string()).name("visibility_key"),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  qx: __t.f32(),
  qy: __t.f32(),
  qz: __t.f32(),
  qw: __t.f32(),
  sx: __t.f32(),
  sy: __t.f32(),
  sz: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  simulationTick: __t.u32().name("simulation_tick"),
  lifecycleState: __t.string().name("lifecycle_state"),
  stateJson: __t.string().name("state_json"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
