// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerSlot: __t.u32().name("player_slot"),
  inputSeq: __t.u64().name("input_seq"),
  clientTick: __t.u32().name("client_tick"),
  inputKind: __t.string().name("input_kind"),
  inputJson: __t.string().name("input_json"),
  createdAt: __t.u64().name("created_at"),
});
