// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  originSlot: __t.option(__t.u32()).name("origin_slot"),
  targetEntityId: __t.option(__t.u64()).name("target_entity_id"),
  eventKind: __t.string().name("event_kind"),
  eventScope: __t.string().name("event_scope"),
  replicationGroup: __t.string().name("replication_group"),
  visibilityScope: __t.string().name("visibility_scope"),
  visibilityKey: __t.option(__t.string()).name("visibility_key"),
  simulationTick: __t.u32().name("simulation_tick"),
  dataJson: __t.string().name("data_json"),
  createdAt: __t.u64().name("created_at"),
});
