// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.u64(),
  entityKey: __t.string(),
  archetype: __t.string(),
  parentEntityId: __t.option(__t.u64()),
  ownerSlot: __t.i32(),
  authority: __t.string(),
  replicationGroup: __t.string(),
  zoneKey: __t.string(),
  visibilityScope: __t.string(),
  visibilityKey: __t.option(__t.string()),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  qx: __t.f32(),
  qy: __t.f32(),
  qz: __t.f32(),
  qw: __t.f32(),
  sx: __t.f32(),
  sy: __t.f32(),
  sz: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  simulationTick: __t.u32(),
  lifecycleState: __t.string(),
  stateJson: __t.string(),
};
