// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  entityId: __t.u64().name("entity_id"),
  componentName: __t.string().name("component_name"),
  schemaKey: __t.string().name("schema_key"),
  replicationGroup: __t.string().name("replication_group"),
  visibilityScope: __t.string().name("visibility_scope"),
  visibilityKey: __t.option(__t.string()).name("visibility_key"),
  ownerSlot: __t.i32().name("owner_slot"),
  dataJson: __t.string().name("data_json"),
  updatedAt: __t.u64().name("updated_at"),
});
