// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerIdentity: __t.identity().name("player_identity"),
  convexUserId: __t.string().name("convex_user_id"),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.string().name("avatar_url"),
  slot: __t.u32(),
  score: __t.i64(),
  status: __t.string(),
  isHost: __t.u8().name("is_host"),
  metadataJson: __t.string().name("metadata_json"),
  joinedAt: __t.u64().name("joined_at"),
  lastSeenAt: __t.u64().name("last_seen_at"),
});
