// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerSlot: __t.u32().name("player_slot"),
  turnNumber: __t.u32().name("turn_number"),
  actionType: __t.string().name("action_type"),
  payloadJson: __t.string().name("payload_json"),
  resultJson: __t.string().name("result_json"),
  timestamp: __t.u64(),
});
