// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  joinCode: __t.string().name("join_code"),
  hostIdentity: __t.identity().name("host_identity"),
  hostConvexId: __t.string().name("host_convex_id"),
  gameType: __t.string().name("game_type"),
  status: __t.string(),
  configJson: __t.string().name("config_json"),
  stateJson: __t.string().name("state_json"),
  currentTurnPlayerSlot: __t.u32().name("current_turn_player_slot"),
  turnNumber: __t.u32().name("turn_number"),
  maxPlayers: __t.u32().name("max_players"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  startedAt: __t.u64().name("started_at"),
  endedAt: __t.u64().name("ended_at"),
});
