// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  gameId: __t.string().name("game_id"),
  joinCode: __t.string().name("join_code"),
  hostIdentity: __t.identity().name("host_identity"),
  hostUserId: __t.string().name("host_user_id"),
  gameType: __t.string().name("game_type"),
  lifecycleState: __t.string().name("lifecycle_state"),
  phaseKey: __t.string().name("phase_key"),
  runtimeKind: __t.string().name("runtime_kind"),
  rulesetKey: __t.string().name("ruleset_key"),
  minPlayers: __t.u32().name("min_players"),
  maxPlayers: __t.u32().name("max_players"),
  activeTurnSlot: __t.i32().name("active_turn_slot"),
  simulationTick: __t.u32().name("simulation_tick"),
  tickRateHz: __t.u32().name("tick_rate_hz"),
  snapshotRateHz: __t.u32().name("snapshot_rate_hz"),
  interestMode: __t.string().name("interest_mode"),
  partitionSize: __t.f32().name("partition_size"),
  publicStateJson: __t.string().name("public_state_json"),
  metadataJson: __t.string().name("metadata_json"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  startedAt: __t.u64().name("started_at"),
  endedAt: __t.u64().name("ended_at"),
});
