// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameActions = __t.object("GameActions", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerSlot: __t.u32(),
  turnNumber: __t.u32(),
  actionType: __t.string(),
  payloadJson: __t.string(),
  resultJson: __t.string(),
  timestamp: __t.u64(),
});
export type GameActions = __Infer<typeof GameActions>;

export const GameChat = __t.object("GameChat", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerSlot: __t.u32(),
  displayName: __t.string(),
  message: __t.string(),
  messageType: __t.string(),
  timestamp: __t.u64(),
});
export type GameChat = __Infer<typeof GameChat>;

export const GameObjects = __t.object("GameObjects", {
  id: __t.u64(),
  sessionId: __t.u64(),
  objectType: __t.string(),
  objectKey: __t.string(),
  ownerSlot: __t.i32(),
  positionJson: __t.string(),
  stateJson: __t.string(),
  sortOrder: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type GameObjects = __Infer<typeof GameObjects>;

export const GamePlayers = __t.object("GamePlayers", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  convexUserId: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  slot: __t.u32(),
  score: __t.i64(),
  status: __t.string(),
  isHost: __t.u8(),
  metadataJson: __t.string(),
  joinedAt: __t.u64(),
  lastSeenAt: __t.u64(),
});
export type GamePlayers = __Infer<typeof GamePlayers>;

export const GameSessions = __t.object("GameSessions", {
  sessionId: __t.u64(),
  joinCode: __t.string(),
  hostIdentity: __t.identity(),
  hostConvexId: __t.string(),
  gameType: __t.string(),
  status: __t.string(),
  configJson: __t.string(),
  stateJson: __t.string(),
  currentTurnPlayerSlot: __t.u32(),
  turnNumber: __t.u32(),
  maxPlayers: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  startedAt: __t.u64(),
  endedAt: __t.u64(),
});
export type GameSessions = __Infer<typeof GameSessions>;

export const GameTickSchedule = __t.object("GameTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionId: __t.u64(),
});
export type GameTickSchedule = __Infer<typeof GameTickSchedule>;

export const IdentityMap = __t.object("IdentityMap", {
  id: __t.u64(),
  stdbIdentity: __t.identity(),
  convexUserId: __t.string(),
  displayName: __t.string(),
  registeredAt: __t.u64(),
});
export type IdentityMap = __Infer<typeof IdentityMap>;

export const MyPrivateState = __t.object("MyPrivateState", {});
export type MyPrivateState = __Infer<typeof MyPrivateState>;

export const MyPrivateStateRow = __t.object("MyPrivateStateRow", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  stateKey: __t.string(),
  stateValue: __t.string(),
  updatedAt: __t.u64(),
});
export type MyPrivateStateRow = __Infer<typeof MyPrivateStateRow>;

export const PlayerPrivateState = __t.object("PlayerPrivateState", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  stateKey: __t.string(),
  stateValue: __t.string(),
  updatedAt: __t.u64(),
});
export type PlayerPrivateState = __Infer<typeof PlayerPrivateState>;

