export const ORCHESTRATOR_HISTORY_MAX_TOKENS = 24_000;
export const SUBAGENT_HISTORY_MAX_TOKENS = 20_000;
export const TASK_DELIVERY_HISTORY_MAX_TOKENS = 10_000;
export const AUTOMATION_HISTORY_MAX_TOKENS = 18_000;
