export const STELLA_BROWSER_BRIDGE_PROVIDER = "extension";
export const STELLA_BROWSER_BRIDGE_SESSION = "stella-app";
export const STELLA_BROWSER_BRIDGE_PORT = "9224";
export const STELLA_BROWSER_BRIDGE_TOKEN = "";

export const getStellaBrowserBridgeEnv = (): Record<string, string> => ({
  STELLA_BROWSER_PROVIDER: STELLA_BROWSER_BRIDGE_PROVIDER,
  STELLA_BROWSER_SESSION: STELLA_BROWSER_BRIDGE_SESSION,
  STELLA_BROWSER_EXT_PORT: STELLA_BROWSER_BRIDGE_PORT,
  STELLA_BROWSER_EXT_TOKEN: STELLA_BROWSER_BRIDGE_TOKEN,
});
