// ---------------------------------------------------------------------------
// Shared bridge HMAC signing helpers (inlined into each bridge code template)
// ---------------------------------------------------------------------------

/* eslint-disable no-useless-escape */
export const BRIDGE_HMAC_HELPERS = [
  `const bytesToHex = (bytes) =>`,
  `  Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");`,
  ``,
  `async function getBridgeMacKey() {`,
  `  if (!bridgeMacKeyPromise) {`,
  `    const encoder = new TextEncoder();`,
  `    bridgeMacKeyPromise = crypto.subtle.importKey(`,
  `      "raw",`,
  `      encoder.encode(config.webhookSecret),`,
  `      { name: "HMAC", hash: "SHA-256" },`,
  `      false,`,
  `      ["sign"],`,
  `    );`,
  `  }`,
  `  return bridgeMacKeyPromise;`,
  `}`,
  ``,
  `async function signedPost(url, body) {`,
  `  const payload = JSON.stringify(body);`,
  `  const timestamp = Math.floor(Date.now() / 1000).toString();`,
  "  const nonce = typeof crypto.randomUUID === \"function\"",
  "    ? crypto.randomUUID()",
  "    : `${Date.now()}-${Math.random().toString(16).slice(2)}`;",
  `  const key = await getBridgeMacKey();`,
  `  const encoder = new TextEncoder();`,
  `  const mac = await crypto.subtle.sign(`,
  `    "HMAC",`,
  `    key,`,
  "    encoder.encode(`${timestamp}.${nonce}.${payload}`),",
  `  );`,
  `  const signature = bytesToHex(new Uint8Array(mac));`,
  ``,
  `  return await fetch(url, {`,
  `    method: "POST",`,
  `    headers: {`,
  `      "Content-Type": "application/json",`,
  `      "x-bridge-timestamp": timestamp,`,
  `      "x-bridge-nonce": nonce,`,
  `      "x-bridge-signature": signature,`,
  `    },`,
  `    body: payload,`,
  `  });`,
  `}`,
].join("\n");
/* eslint-enable no-useless-escape */
